<?php declare(strict_types=1);
return [
    '/' => 'HomeController@index',
    '/article/{id}' => 'ArticleController@show',
    '/category/{slug}' => 'CategoryController@index',
    '/tag/{slug}' => 'TagController@index',
    '/page/{slug}' => 'PageController@show',
    '/login' => 'AuthController@login',
    '/logout' => 'AuthController@logout',
    '/register' => 'AuthController@register',
    '/admin' => 'AdminController@dashboard',
    '/admin/articles' => 'AdminController@articles',
    '/admin/article/create' => 'AdminController@createArticle',
    '/admin/article/edit/{id}' => 'AdminController@editArticle',
    '/admin/article/delete/{id}' => 'AdminController@deleteArticle',
    '/admin/categories' => 'AdminController@categories',
    '/admin/category/create' => 'AdminController@createCategory',
    '/admin/category/edit/{id}' => 'AdminController@editCategory',
    '/admin/category/delete/{id}' => 'AdminController@deleteCategory',
    '/admin/users' => 'AdminController@users',
    '/admin/user/role' => 'AdminController@updateUserRole',
    '/admin/settings' => 'AdminController@settings',
    '/admin/cache/clear' => 'AdminController@clearCache',
    '/admin/profile' => 'AdminController@profile',
    '/admin/profile/update' => 'AdminController@updateProfile',
    '/admin/profile/password' => 'AdminController@updatePassword',
];